### ISSUE TITLE
Cleanup imports in views.py

### ISSUE THREAD

**Issue by GhalyahFA** [AhmedHajeyah/wil#3]
```
from django.shortcuts import render, redirect
from telnetlib import LOGOUT
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import RegistrationForm, LoginForm
from .models import Recipe
```

1.Why do you need this ?` from telnetlib import LOGOUT`? this is enough `django.contrib.auth import authenticate, login, logout`

2.` from django.shortcuts import render ` duplicate of from django.shortcuts import render, redirect

3`.from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView`
Do you plan on using the builtin generic views for the entire crud?

**Comment by AhmedHajeyah** [comment]
cleaned as mentioned above
