### ISSUE TITLE
login html template

### ISSUE THREAD

**Issue by GhalyahFA** [AhmedHajeyah/wil#5]
1.Login page says 'sign up 'in  title of the form 
2. link at the bottom says login even though it's in the login page

<img width="649" alt="Screen Shot 2022-08-17 at 5 33 23 PM" src="https://user-images.githubusercontent.com/10036755/185162557-932c7a2f-82db-478d-8185-c9706b2b00ae.png">

<img width="647" alt="Screen Shot 2022-08-17 at 5 35 48 PM" src="https://user-images.githubusercontent.com/10036755/185163662-108017a3-e84a-458b-89be-7e414ea12f15.png">

**Comment by AhmedHajeyah** [comment]
corrected
